### PR TITLE
added Revit 2022 RevitAPI.chm renamed to 2022.chm

### PR DESCRIPTION
**Pull request by jeremytammik**
[master aea2089] added Revit 2022 RevitAPI.chm renamed to 2022.chm
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 2022.chm
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 54.10 MiB | 3.43 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File 2022.chm is 54.91 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
To github.com:jeremytammik/revit-api-chms.git

### CODE REVIEW

**Comment by jeremytammik** [comment]
Maybe consider configuring Git Large File Storage - https://git-lfs.github.com ?

**Comment by gtalarico** [comment]
Duplicate of #3 ?

**Comment by jeremytammik** [comment]
Yes, absolutely. Sorry, did not check beforehand.

**Comment by gtalarico** [comment]
no problem. 
@johnpierson is just too fast for us @jeremytammik  :)
PS: added LFS

**Comment by jeremytammik** [comment]
:-) 
fastest in the west.

**Comment by gtalarico** [comment]
@jeremytammik after switching over to LFS this repo is consuming all my quota and Github is billing me $$$ 😱 
Could we move this over to an Autodesk accnt? or a @jeremytammik  accnt? And you can bill ADSK for it?
image

**Comment by jeremytammik** [comment]
@gtalarico oh. i was not aware of that.  i use LFS myself for the building coder but remain below the quota. i'll check about an autodesk account.

**Comment by jeremytammik** [comment]
How does this look?

https://github.com/Autodesk-Forge/revit-api-chms

I just set it up and am in the process of copying the files to it...

**Comment by jeremytammik** [comment]
trouble copying the files...

$ git push
Enumerating objects: 25, done.
Counting objects: 100% (25/25), done.
Delta compression using up to 12 threads
Connection to github.com closed by remote host.
fatal: the remote end hung up unexpectedly
Compressing objects: 100% (23/23), done.
fatal: the remote end hung up unexpectedly
$

**Comment by jeremytammik** [comment]
i tried setting the buffer size, then set gc aggressive. maybe i had no set up lfs properly beforehand, though. now i set up lfs and uploading seems to be working fine.

**Comment by jeremytammik** [comment]
now all is done and complete

**Comment by jeremytammik** [comment]
My colleagues suggested a better place for the repo, and I moved to the ADN-DevTech organisation, which is more desktop focussed than the Autodesk-Forge one:

https://github.com/ADN-DevTech/revit-api-chms

**Pull request closed without merging**
